import type { Hobby } from './types';

export const MATERIALS = {
  paper: 'Paper and a pen',
  camera: 'A phone camera',
  headphones: 'Headphones',
  kitchen: 'A kitchen',
  instrument: 'A musical instrument',
  art: 'Pencils or paints',
  yarn: 'Yarn and a hook or needles',
  laptop: 'A laptop',
  book: 'A book',
  shoes: 'Comfortable shoes',
  plants: 'A plant or seeds',
} as const;
export type Material = keyof typeof MATERIALS;

const h = (hobby: Omit<Hobby, 'materials'> & { materials: Material[] }): Hobby => hobby;

export const HOBBIES: Hobby[] = [
  h({
    id: 'sketching',
    title: 'Pocket sketching',
    category: 'making',
    description: 'Quick, loose drawings of whatever is in front of you.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free with any pen',
    minMinutes: 5,
    place: 'either',
    company: 'solo',
    forSkill: 'any',
    materials: ['paper'],
    starter: {
      title: 'Draw three objects on your desk',
      steps: ['Pick three things within reach', 'Give each one two minutes, no erasing', 'Circle the one you like most'],
    },
  }),
  h({
    id: 'watercolour',
    title: 'Watercolour washes',
    category: 'making',
    description: 'Layering soft colour on paper and letting the water do some of the work.',
    difficulty: 'steady',
    cost: 'low',
    costNote: 'A starter set costs little',
    minMinutes: 15,
    place: 'indoor',
    company: 'solo',
    forSkill: 'any',
    materials: ['art', 'paper'],
    starter: {
      title: 'Paint a five-colour gradient',
      steps: ['Wet a strip of paper', 'Drop in one colour at each end', 'Watch them meet, then add three more strips'],
    },
  }),
  h({
    id: 'crochet',
    title: 'Crochet',
    category: 'making',
    description: 'Turning one long thread into something you can hold.',
    difficulty: 'steady',
    cost: 'low',
    costNote: 'A hook and one ball of yarn',
    minMinutes: 15,
    place: 'indoor',
    company: 'either',
    forSkill: 'any',
    materials: ['yarn'],
    starter: {
      title: 'Make a chain of twenty stitches',
      steps: ['Tie a slip knot', 'Follow a short chain-stitch video', 'Chain twenty and count them'],
    },
  }),
  h({
    id: 'origami',
    title: 'Origami',
    category: 'making',
    description: 'Folding a flat square into a small, precise object.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Any square of paper',
    minMinutes: 10,
    place: 'indoor',
    company: 'solo',
    forSkill: 'any',
    materials: ['paper'],
    starter: {
      title: 'Fold a paper crane',
      steps: ['Cut a square from any sheet', 'Follow one crane diagram slowly', 'Fold a second one from memory'],
    },
  }),
  h({
    id: 'photo-walk',
    title: 'Photo walk',
    category: 'nature',
    description: 'Walking slowly and noticing light, texture and shape.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free with your phone',
    minMinutes: 10,
    place: 'outdoor',
    company: 'either',
    forSkill: 'any',
    materials: ['camera'],
    starter: {
      title: 'Find five things that are the same colour',
      steps: ['Choose a colour before you leave', 'Take one photo of each find', 'Keep your favourite, delete the rest'],
    },
  }),
  h({
    id: 'birdwatching',
    title: 'Birdwatching',
    category: 'nature',
    description: 'Sitting still long enough to notice who lives nearby.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 10,
    place: 'outdoor',
    company: 'solo',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Spot and describe three birds',
      steps: ['Find a window or a bench', 'Note size, colour and sound of each bird', 'Look one of them up afterwards'],
    },
  }),
  h({
    id: 'balcony-garden',
    title: 'Small-space gardening',
    category: 'nature',
    description: 'Growing herbs or greens on a sill or balcony.',
    difficulty: 'steady',
    cost: 'low',
    costNote: 'A pot, soil and seeds',
    minMinutes: 15,
    place: 'either',
    company: 'solo',
    forSkill: 'any',
    materials: ['plants'],
    starter: {
      title: 'Plant one pot of herbs',
      steps: ['Fill a pot with soil', 'Sow seeds at the depth on the packet', 'Water and put it where it gets light'],
    },
  }),
  h({
    id: 'ukulele',
    title: 'Ukulele',
    category: 'music',
    description: 'A small instrument where four chords already play hundreds of songs.',
    difficulty: 'steady',
    cost: 'low',
    costNote: 'A beginner ukulele is inexpensive',
    minMinutes: 15,
    place: 'indoor',
    company: 'either',
    forSkill: 'beginner',
    materials: ['instrument'],
    starter: {
      title: 'Learn C, A minor and F',
      steps: ['Tune with a free tuner app', 'Hold each chord for four strums', 'Switch between them slowly'],
    },
  }),
  h({
    id: 'rhythm',
    title: 'Body percussion',
    category: 'music',
    description: 'Making rhythms with your hands, feet and voice.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 5,
    place: 'either',
    company: 'either',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Clap a four-beat pattern',
      steps: ['Clap, snap, tap, rest', 'Loop it for one minute', 'Add a stomp on beat three'],
    },
  }),
  h({
    id: 'active-listening',
    title: 'Deep listening',
    category: 'music',
    description: 'Listening to one album start to finish with nothing else open.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 15,
    place: 'indoor',
    company: 'solo',
    forSkill: 'any',
    materials: ['headphones'],
    starter: {
      title: 'Listen to three songs from an album you have never heard',
      steps: ['Put the phone face down', 'Listen with your eyes closed', 'Write one line about each song'],
    },
  }),
  h({
    id: 'music-production',
    title: 'Beat making',
    category: 'music',
    description: 'Building short loops with free music software.',
    difficulty: 'stretch',
    cost: 'free',
    costNote: 'Free software',
    minMinutes: 30,
    place: 'indoor',
    company: 'solo',
    forSkill: 'experienced',
    materials: ['laptop', 'headphones'],
    starter: {
      title: 'Make an eight-bar drum loop',
      steps: ['Open a free browser sequencer', 'Place kick, snare and hi-hat', 'Change one sound and compare'],
    },
  }),
  h({
    id: 'stretching',
    title: 'Mobility flow',
    category: 'movement',
    description: 'Gentle stretches that undo hours of sitting.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 5,
    place: 'indoor',
    company: 'solo',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Five stretches, one minute each',
      steps: ['Neck rolls', 'Shoulder opener against a wall', 'Hip flexor lunge, each side'],
    },
  }),
  h({
    id: 'running',
    title: 'Run and walk',
    category: 'movement',
    description: 'Alternating easy running with walking until running feels easy.',
    difficulty: 'steady',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 15,
    place: 'outdoor',
    company: 'either',
    forSkill: 'any',
    materials: ['shoes'],
    starter: {
      title: 'Run one minute, walk two, five times',
      steps: ['Warm up with a brisk walk', 'Repeat the run-walk cycle', 'Cool down and stretch your calves'],
    },
  }),
  h({
    id: 'dance',
    title: 'Dance basics',
    category: 'movement',
    description: 'Learning one short routine, one count at a time.',
    difficulty: 'steady',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 10,
    place: 'indoor',
    company: 'either',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Learn the first eight counts of a routine',
      steps: ['Pick a beginner tutorial', 'Learn it at half speed', 'Run it three times with the music'],
    },
  }),
  h({
    id: 'badminton',
    title: 'Badminton',
    category: 'movement',
    description: 'A fast, friendly game you can play almost anywhere with two people.',
    difficulty: 'easy',
    cost: 'low',
    costNote: 'Two rackets and shuttles',
    minMinutes: 30,
    place: 'outdoor',
    company: 'social',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Keep a rally going for twenty hits',
      steps: ['Find a partner', 'Hit gently, aim for each other', 'Count your longest rally'],
    },
  }),
  h({
    id: 'journaling',
    title: 'Journaling',
    category: 'words',
    description: 'Writing a few honest lines to clear your head.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 5,
    place: 'either',
    company: 'solo',
    forSkill: 'any',
    materials: ['paper'],
    starter: {
      title: 'Write one page without stopping',
      steps: ['Set a single prompt: what is on my mind?', 'Keep the pen moving', 'Underline one sentence worth keeping'],
    },
  }),
  h({
    id: 'poetry',
    title: 'Short poems',
    category: 'words',
    description: 'Saying something true in very few words.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 10,
    place: 'either',
    company: 'solo',
    forSkill: 'any',
    materials: ['paper'],
    starter: {
      title: 'Write three haiku about today',
      steps: ['Five, seven, five syllables', 'One about something you saw', 'One about something you heard'],
    },
  }),
  h({
    id: 'reading',
    title: 'Reading for fun',
    category: 'words',
    description: 'Short stories or a novel, read slowly, for no reason.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free from a library',
    minMinutes: 15,
    place: 'either',
    company: 'solo',
    forSkill: 'any',
    materials: ['book'],
    starter: {
      title: 'Read one short story',
      steps: ['Choose a story under twenty pages', 'Read somewhere comfortable', 'Tell someone one thing that happened'],
    },
  }),
  h({
    id: 'language',
    title: 'A new language',
    category: 'mind',
    description: 'A few words a day until a real sentence appears.',
    difficulty: 'steady',
    cost: 'free',
    costNote: 'Free apps and podcasts',
    minMinutes: 10,
    place: 'either',
    company: 'either',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Learn to introduce yourself',
      steps: ['Pick a language', 'Learn hello, my name is, and I like', 'Say all three out loud without notes'],
    },
  }),
  h({
    id: 'chess',
    title: 'Chess puzzles',
    category: 'mind',
    description: 'Short tactical puzzles that train patience and pattern spotting.',
    difficulty: 'steady',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 10,
    place: 'indoor',
    company: 'either',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Solve five mate-in-one puzzles',
      steps: ['Use a free puzzle site or a book', 'Find every check before moving', 'Note the pattern you missed'],
    },
  }),
  h({
    id: 'meditation',
    title: 'Breathing practice',
    category: 'mind',
    description: 'A few quiet minutes paying attention to your breath.',
    difficulty: 'easy',
    cost: 'free',
    costNote: 'Free',
    minMinutes: 5,
    place: 'either',
    company: 'solo',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Ten slow breaths, three rounds',
      steps: ['Sit comfortably', 'Breathe in for four, out for six', 'Rest one minute between rounds'],
    },
  }),
  h({
    id: 'cooking',
    title: 'Simple cooking',
    category: 'food',
    description: 'One dish, learned properly, then made your own.',
    difficulty: 'steady',
    cost: 'low',
    costNote: 'Cost of ingredients',
    minMinutes: 30,
    place: 'indoor',
    company: 'either',
    forSkill: 'any',
    materials: ['kitchen'],
    starter: {
      title: 'Make a perfect omelette or upma',
      steps: ['Prepare everything before turning on the heat', 'Cook on medium, not high', 'Taste and adjust the salt'],
    },
  }),
  h({
    id: 'tea',
    title: 'Tea tasting',
    category: 'food',
    description: 'Brewing carefully and noticing the difference.',
    difficulty: 'easy',
    cost: 'low',
    costNote: 'Two kinds of tea',
    minMinutes: 10,
    place: 'indoor',
    company: 'either',
    forSkill: 'any',
    materials: ['kitchen'],
    starter: {
      title: 'Brew one tea at two strengths',
      steps: ['Steep one cup for two minutes', 'Steep another for five', 'Write how they differ'],
    },
  }),
  h({
    id: 'baking',
    title: 'Baking',
    category: 'food',
    description: 'Precise, patient, and you get to eat the result.',
    difficulty: 'stretch',
    cost: 'flexible',
    costNote: 'Ingredients and an oven',
    minMinutes: 60,
    place: 'indoor',
    company: 'either',
    forSkill: 'any',
    materials: ['kitchen'],
    starter: {
      title: 'Mix a mug cake',
      steps: ['Measure flour, sugar, cocoa and milk', 'Microwave in short bursts', 'Note what you would change next time'],
    },
  }),
  h({
    id: 'coding-art',
    title: 'Creative coding',
    category: 'tech',
    description: 'Writing small programs that draw shapes and patterns.',
    difficulty: 'steady',
    cost: 'free',
    costNote: 'Free in the browser',
    minMinutes: 15,
    place: 'indoor',
    company: 'solo',
    forSkill: 'any',
    materials: ['laptop'],
    starter: {
      title: 'Draw a grid of random circles',
      steps: ['Open a free browser sketch editor', 'Loop over rows and columns', 'Randomise the size of each circle'],
    },
  }),
  h({
    id: 'electronics',
    title: 'Tinkering with electronics',
    category: 'tech',
    description: 'Making lights blink and buttons do things.',
    difficulty: 'stretch',
    cost: 'flexible',
    costNote: 'A starter kit',
    minMinutes: 30,
    place: 'indoor',
    company: 'either',
    forSkill: 'experienced',
    materials: ['laptop'],
    starter: {
      title: 'Blink an LED in a simulator',
      steps: ['Open a free circuit simulator', 'Wire an LED and resistor', 'Change the blink speed'],
    },
  }),
  h({
    id: 'board-games',
    title: 'Board game night',
    category: 'mind',
    description: 'An hour around a table instead of around a feed.',
    difficulty: 'easy',
    cost: 'low',
    costNote: 'Borrow a game or use cards',
    minMinutes: 30,
    place: 'indoor',
    company: 'social',
    forSkill: 'any',
    materials: [],
    starter: {
      title: 'Teach a friend one card game',
      steps: ['Pick a game with short rules', 'Play one practice round', 'Play best of three'],
    },
  }),
];
