// Writes the hobby catalogue from src/domain/catalog.ts into a migration, so the app and the
// database always agree. Run: npm run db:hobbies  (CI fails if the file is out of date).
import { writeFileSync } from 'node:fs';

import { HOBBIES } from '../src/domain/catalog.ts';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[]) => (a.length ? `array[${a.map(q).join(', ')}]` : `'{}'::text[]`);

const rows = HOBBIES.map(
  (h) =>
    `  (${[
      q(h.id),
      q(h.title),
      q(h.category),
      q(h.description),
      q(h.difficulty),
      q(h.cost),
      q(h.costNote),
      h.minMinutes,
      q(h.place),
      q(h.company),
      q(h.forSkill),
      arr(h.materials),
      q(h.starter.title),
      arr(h.starter.steps),
    ].join(', ')})`,
);

const sql = `-- Generated by scripts/gen-hobbies-sql.mts from src/domain/catalog.ts. Do not edit by hand.
insert into public.hobbies (
  id, title, category, description, difficulty, estimated_cost, cost_note, estimated_duration,
  activity_place, activity_company, for_skill, materials, starter_title, starter_steps
) values
${rows.join(',\n')}
on conflict (id) do update set
  title = excluded.title, category = excluded.category, description = excluded.description,
  difficulty = excluded.difficulty, estimated_cost = excluded.estimated_cost, cost_note = excluded.cost_note,
  estimated_duration = excluded.estimated_duration, activity_place = excluded.activity_place,
  activity_company = excluded.activity_company, for_skill = excluded.for_skill, materials = excluded.materials,
  starter_title = excluded.starter_title, starter_steps = excluded.starter_steps, is_active = true;
`;

writeFileSync(new URL('../supabase/migrations/20261009000100_hobbies.sql', import.meta.url), sql);
console.log(`Wrote ${HOBBIES.length} hobbies.`);
